# Colors (One Dark)

# Default colors
[colors.primary]
background = '#282c34'
foreground = '#abb2bf'

# Normal colors
[colors.normal]
black = '#1e2127'
red = '#e06c75'
green = '#98c379'
yellow = '#d19a66'
blue = '#61afef'
magenta = '#c678dd'
cyan = '#56b6c2'
white = '#abb2bf'

# Bright colors
[colors.bright]
black = '#5c6370'
red = '#e06c75'
green = '#98c379'
yellow = '#d19a66'
blue = '#61afef'
magenta = '#c678dd'
cyan = '#56b6c2'
white = '#ffffff'


[colors.hints]
start = { foreground = '#908caa', background = '#2a273f' }
end = { foreground = '#6e6a86', background = '#2a273f' }

[font]
normal.family = "Iosevka"
bold.family = "Iosevka"
italic.family = "Iosevka"
size = 14.0

[window]
opacity = 0.98
blur = true
padding = { x = 5, y = 5 }
dimensions = { columns = 140, lines = 25 }
# decorations = "none"

[keyboard]
bindings = [
  # Open a new terminal
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
]

[shell]
program = "/bin/tmux"
args = ["new", "-A", "-s", "main"]
