
[font]
size = 15

[font.normal]
family = "Iosevka"

[font.bold]
family = "Iosevka"

[font.italic]
family = "Iosevka"

[window]
opacity = 0.93
blur = true
decorations = "none"

[window.padding]
x = 10
y = 10

[window.dimensions]
columns = 110
lines = 28


[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
action = "SpawnNewInstance"

[terminal.shell]
program = "/bin/tmux"
args = ["new", "-A", "-s", "alacritty"]

[general]
import = [
  "/home/mohammed/.local/share/pnpm/global/5/.pnpm/alacritty-themes@6.0.2/node_modules/alacritty-themes/themes/Ayu-Dark.toml",
]
