# Theme: enfocado_dark
# Source:  https://github.com/wuelnerdotexe/vim-enfocado

# Default colors
[colors.primary]
background = '#181818'
foreground = '#b9b9b9'

# Normal colors
[colors.normal]
black = '#3b3b3b'
red = '#ed4a46'
green = '#70b433'
yellow = '#dbb32d'
blue = '#368aeb'
magenta = '#eb6eb7'
cyan = '#3fc5b7'
white = '#b9b9b9'

# Bright colors
[colors.bright]
black = '#777777'
red = '#ff5e56'
green = '#83c746'
yellow = '#efc541'
blue = '#4f9cfe'
magenta = '#ff81ca'
cyan = '#56d8c9'
white = '#dedede'


[colors.hints]
start = { foreground = '#908caa', background = '#2a273f' }
end = { foreground = '#6e6a86', background = '#2a273f' }

[font]
normal.family = "Iosevka"
bold.family = "Iosevka"
italic.family = "Iosevka"
size = 14.0

[window]
opacity = 0.98
blur = true
padding = { x = 5, y = 5 }
dimensions = { columns = 140, lines = 25 }
# decorations = "none"

[keyboard]
bindings = [
  # Open a new terminal
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
]

[shell]
program = "/bin/tmux"
args = ["new", "-A", "-s", "main"]
