
[font]
size = 12

[font.normal]
family = "Cascadia Code PL"

[font.bold]
family = "Cascadia Code PL"

[font.italic]
family = "Cascadia Code PL"

[window]
opacity = 0.5
blur = true
[window.padding]
x = 10
y = 10

[window.dimensions]
columns = 120
lines = 38


[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
action = "SpawnNewInstance"

[terminal.shell]
program = "/bin/tmux"
args = ["new", "-A", "-s", "alacritty"]

[general]
import = [
  "/home/mohammed/.local/share/pnpm/global/5/.pnpm/alacritty-themes@6.0.2/node_modules/alacritty-themes/themes/Ayu-Dark.toml",
]
