[colors.primary]
background = "#15141b"
foreground = "#edecee"

[colors.cursor]
cursor = "#a277ff"

[colors.selection]
text = "CellForeground"
background = "#29263c"

[colors.normal]
black = "#110f18"
red = "#ff6767"
green = "#61ffca"
yellow = "#ffca85"
blue = "#a277ff"
magenta = "#a277ff"
cyan = "#61ffca"
white = "#edecee"

[colors.bright]
black = "#4d4d4d"
red = "#ff6767"
green = "#61ffca"
yellow = "#ffca85"
blue = "#a277ff"
magenta = "#a277ff"
cyan = "#61ffca"
white = "#edecee"

[colors.hints]
start = { foreground = '#908caa', background = '#2a273f' }
end = { foreground = '#6e6a86', background = '#2a273f' }

[font]
normal.family = "Recursive Monospace Casual"
bold.family = "Recursive Monospace Casual"
italic.family = "Recursive Monospace Casual"
size = 14.0

[window]
opacity = 0.90
blur = true
padding = { x = 5, y = 5 }
dimensions = { columns = 120, lines = 30 }
#decorations = "none"

[keyboard]
bindings = [
  # Open a new terminal
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
]

[shell]
program = "/bin/tmux"
args = ["new", "-A", "-s", "main"]
