[colors.primary]
background = "#15141b"
foreground = "#edecee"

[colors.cursor]
cursor = "#a277ff"

[colors.selection]
text = "CellForeground"
background = "#29263c"

[colors.normal]
black = "#110f18"
red = "#ff6767"
green = "#61ffca"
yellow = "#ffca85"
blue = "#a277ff"
magenta = "#a277ff"
cyan = "#61ffca"
white = "#edecee"

[colors.bright]
black = "#4d4d4d"
red = "#ff6767"
green = "#61ffca"
yellow = "#ffca85"
blue = "#a277ff"
magenta = "#a277ff"
cyan = "#61ffca"
white = "#edecee"

[font]
normal.family = "Cascadia Code"
bold.family = "Cascadia Code"
italic.family = "Cascadia Code"
size = 14.0

[window]
opacity = 0.9
blur = true
padding = { x = 5, y = 5 }
# decorations = "none"
dimensions = { columns = 100, lines = 30 }

[keyboard]
bindings = [
  # Open a new terminal
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
]

[shell]
program = "/bin/tmux"
args = ["new", "-A", "-s", "main"]
