
[font]
size = 12

  [font.normal]
  style = "bold"
  family = "JetbrainsMonoNL Nerd font"

  [font.bold]
  family = "JetbrainsMonoNL Nerd font"

  [font.italic]
  family = "Iosevka"

[window]
opacity = 0.95
blur = true

  [window.padding]
  x = 10
  y = 10

  [window.dimensions]
  columns = 120
  lines = 30

[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
action = "SpawnNewInstance"

[terminal.shell]
program = "/bin/tmux"
args = [ "new", "-A", "-s", "main" ]

[general]
import = [
  "/home/mohammed/.local/share/pnpm/global/5/.pnpm/alacritty-themes@6.0.2/node_modules/alacritty-themes/themes/Ayu-Dark.toml"
]
